<a href="https://colab.research.google.com/github/shreyasat27/mahework2025/blob/main/Tier1(myversion).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Install necessary packages
!pip install pyscf > /dev/null
!pip install ase > /dev/null # For easy molecular generation
!pip install geometric
# Import libraries
from pyscf import gto, scf, dft, cc, mcscf, lib
#from pyscf import shci
import numpy as np
import matplotlib.pyplot as plt

print("All packages installed and imported successfully!")

All packages installed and imported successfully!


In [ ]:
!pip install pyberny

In [ ]:
from pyscf import gto, dft, scf, grad, lib
import numpy as np

from pyscf.geomopt import berny_solver
# ==============================
# Cell 1: Define Phenalenyl Radical
# ==============================
phenalenyl_xyz = """
C        0.0000    1.2055    0.0000
C        1.0441    0.6028    0.0000
C        1.0441   -0.6028    0.0000
C        0.0000   -1.2055    0.0000
C       -1.0441   -0.6028    0.0000
C       -1.0441    0.6028    0.0000
C        0.0000    2.6020    0.0000
C        1.2536    3.1029    0.0000
C        2.2977    2.5002    0.0000
C        2.2977    1.2946    0.0000
C        1.2536   -2.5002    0.0000
C        0.0000   -2.6020    0.0000
C       -1.2536   -2.5002    0.0000
H        2.0740    3.6975    0.0000
H        3.2417    2.8749    0.0000
H        3.2417    1.2946    0.0000
H        2.0740   -3.6975    0.0000
H       -2.0740   -3.6975    0.0000
H       -3.2417   -2.8749    0.0000
H       -3.2417   -1.2946    0.0000
H       -2.0740    3.6975    0.0000
"""

mol = gto.M(
    atom=phenalenyl_xyz,
    basis='sto-3g',    # ⚡ FASTER than def2-svp for Colab
    charge=-1,
    spin=1,
    verbose=4
)

print(f"Molecule defined. Number of atoms: {mol.natm}")
print(f"Charge: {mol.charge}, Spin multiplicity: {mol.spin}")


# ==============================
# Cell 2: Geometry Optimization
# ==============================
print("Starting Tier 1a: Geometry Optimization...")

mf = dft.UKS(mol)
mf.xc = 'b3lyp'
mf.max_cycle = 100   # Lower max iterations for speed
mf.kernel()


# Optimize geometry with berny solver
mol_eq = berny_solver.optimize(mf, maxsteps=50, conv_tol=1e-5)

print("Optimized coordinates:")
print(mol_eq.atom_coords())

print("Geometry optimization finished. (Hessian skipped for speed)")
print("⚠️ NOTE: No frequency calculation on Colab to save time.")


# ==============================
# Cell 3: Single Point Energy
# ==============================
print("\nStarting Tier 1b: Single Point Energy & Ground State Characterization...")

mf_final = dft.UKS(mol)
mf_final.xc = 'b3lyp'
mf_final.grids.level = 3  # moderate accuracy
mf_final.kernel()

print(f"Final UKS Energy: {mf_final.e_tot} Hartree")
print(f"Converged SCF: {mf_final.converged}")
print(f"⟨S²⟩ before annihilation: {mf_final.spin_square()[0]}")
print(f"⟨S²⟩ after annihilation: {mf_final.spin_square()[1]}")


# ==============================
# Cell 4: Triplet Calculation (Excited State Gap)
# ==============================
print("\nStarting Tier 1c: Energy Gap to First Excited State...")

mol_triplet = gto.M(
    atom=phenalenyl_xyz,
    basis='sto-3g',
    charge=-1,
    spin=3,  # Quartet (S=3/2)
    verbose=0
)

mf_triplet = dft.UKS(mol_triplet)
mf_triplet.xc = 'b3lyp'
mf_triplet.kernel()

energy_doublet = mf_final.e_tot
energy_triplet = mf_triplet.e_tot
delta_E = (energy_triplet - energy_doublet) * 627.509  # kcal/mol

print(f"Doublet Energy: {energy_doublet} Ha")
print(f"Triplet Energy: {energy_triplet} Ha")
print(f"ΔE (Triplet - Doublet) = {delta_E:.2f} kcal/mol")


# ==============================
# Cell 5: Summary
# ==============================
print("\n" + "="*50)
print("TIER 1 SCREENING SUMMARY: PHENALENYL RADICAL")
print("="*50)

s2_value = mf_final.spin_square()[1]
c1_pass = 0.70 < s2_value < 0.80
c2_pass = delta_E > 5.0

print(f"Criterion 1 (Pure S=1/2 GS): {'PASS' if c1_pass else 'FAIL'} - ⟨S²⟩ = {s2_value:.4f}")
print(f"Criterion 2 (Energy Gap):    {'PASS' if c2_pass else 'FAIL'} - ΔE = {delta_E:.2f} kcal/mol")


System: uname_result(system='Linux', node='148b82fb1410', release='6.1.123+', version='#1 SMP PREEMPT_DYNAMIC Sun Mar 30 16:01:29 UTC 2025', machine='x86_64')  Threads 2
Python 3.12.11 (main, Jun  4 2025, 08:56:18) [GCC 11.4.0]
numpy 1.26.4  scipy 1.16.1  h5py 3.14.0
Date: Mon Sep  1 06:24:49 2025
PySCF version 2.10.0
PySCF path  /usr/local/lib/python3.12/dist-packages/pyscf

[CONFIG] conf_file None
[INPUT] verbose = 4
[INPUT] num. atoms = 21
[INPUT] num. electrons = 87
[INPUT] charge = -1
[INPUT] spin (= nelec alpha-beta = 2S) = 1
[INPUT] symmetry False subgroup None
[INPUT] Mole.unit = angstrom
[INPUT] Symbol           X                Y                Z      unit          X                Y                Z       unit  Magmom
[INPUT]  1 C      0.000000000000   1.205500000000   0.000000000000 AA    0.000000000000   2.278064843163   0.000000000000 Bohr   0.0
[INPUT]  2 C      1.044100000000   0.602800000000   0.000000000000 AA    1.973063046658   1.139126907888   0.000000000000 Bohr  

/usr/local/lib/python3.12/dist-packages/pyscf/dft/libxc.py:511: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '


tot grids = 262000
init E= -499.056807290674
  alpha nocc = 44  HOMO = -0.155015971992432  LUMO = -0.12613643812012
  beta  nocc = 43  HOMO = -0.184046742697496  LUMO = -0.155015971992432

WARN: system HOMO -0.155015971992432 >= system LUMO -0.155015971992432

cycle= 1 E= -491.878351866713  delta_E= 7.18  |g|= 0.441  |ddm|= 5.46
  alpha nocc = 44  HOMO = 0.16365685223439  LUMO = 0.201150890889551
  beta  nocc = 43  HOMO = 0.139559269277517  LUMO = 0.168656321703604
cycle= 2 E= -490.237719391983  delta_E= 1.64  |g|= 1.33  |ddm|= 3.24
  alpha nocc = 44  HOMO = 0.0966169816448547  LUMO = 0.127631349207982
  beta  nocc = 43  HOMO = 0.105068932382182  LUMO = 0.134456025695853
cycle= 3 E= -491.874078731798  delta_E= -1.64  |g|= 0.418  |ddm|= 2.87
  alpha nocc = 44  HOMO = 0.0748217233353765  LUMO = 0.160490928616549
  beta  nocc = 43  HOMO = 0.0797380766724725  LUMO = 0.118275191870027
cycle= 4 E= -492.004571689107  delta_E= -0.13  |g|= 0.207  |ddm|= 1.64
  alpha nocc = 44  HOMO = 0.09377361

INFO:pyscf.geomopt.berny_solver.132696934205296:0 Internal coordinates:


0 * Number of fragments: 4


INFO:pyscf.geomopt.berny_solver.132696934205296:0 * Number of fragments: 4


0 * Number of internal coordinates: 460


INFO:pyscf.geomopt.berny_solver.132696934205296:0 * Number of internal coordinates: 460


0 * Number of strong bonds: 24


INFO:pyscf.geomopt.berny_solver.132696934205296:0 * Number of strong bonds: 24


0 * Number of weak bonds: 15


INFO:pyscf.geomopt.berny_solver.132696934205296:0 * Number of weak bonds: 15


0 * Number of strong angles: 48


INFO:pyscf.geomopt.berny_solver.132696934205296:0 * Number of strong angles: 48


0 * Number of weak angles: 31


INFO:pyscf.geomopt.berny_solver.132696934205296:0 * Number of weak angles: 31


0 * Number of superweak angles: 18


INFO:pyscf.geomopt.berny_solver.132696934205296:0 * Number of superweak angles: 18


0 * Number of strong dihedrals: 94


INFO:pyscf.geomopt.berny_solver.132696934205296:0 * Number of strong dihedrals: 94


0 * Number of weak dihedrals: 230


INFO:pyscf.geomopt.berny_solver.132696934205296:0 * Number of weak dihedrals: 230



Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.000000   1.205500   0.000000    0.000000  0.000000  0.000000
   C   1.044100   0.602800   0.000000    0.000000  0.000000  0.000000
   C   1.044100  -0.602800   0.000000    0.000000  0.000000  0.000000
   C   0.000000  -1.205500   0.000000    0.000000  0.000000  0.000000
   C  -1.044100  -0.602800   0.000000    0.000000  0.000000  0.000000
   C  -1.044100   0.602800   0.000000    0.000000  0.000000  0.000000
   C   0.000000   2.602000   0.000000    0.000000  0.000000  0.000000
   C   1.253600   3.102900   0.000000    0.000000  0.000000  0.000000
   C   2.297700   2.500200   0.000000    0.000000  0.000000  0.000000
   C   2.297700   1.294600   0.000000    0.000000  0.000000  0.000000
   C   1.253600  -2.500200   0.000000    0.000000  0.000000  0.000000
   C   0.000000  -2.602000   0.000000    0.000000  0.000000  0.000000
   C  -1.253600  -2.500200   0.0

INFO:pyscf.geomopt.berny_solver.132696934205296:1 Energy: -492.062839903


1 Minimization on sphere was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:1 Minimization on sphere was performed:


1 * Trust radius: 0.3


INFO:pyscf.geomopt.berny_solver.132696934205296:1 * Trust radius: 0.3


1 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:1 * Number of negative eigenvalues: 0


1 * Lowest eigenvalue: 0.000592


INFO:pyscf.geomopt.berny_solver.132696934205296:1 * Lowest eigenvalue: 0.000592


1 * lambda: -3.19


INFO:pyscf.geomopt.berny_solver.132696934205296:1 * lambda: -3.19


1 Quadratic step: RMS: 0.014, max: 0.116


INFO:pyscf.geomopt.berny_solver.132696934205296:1 Quadratic step: RMS: 0.014, max: 0.116


1 * Predicted energy change: -0.309


INFO:pyscf.geomopt.berny_solver.132696934205296:1 * Predicted energy change: -0.309


1 Total step: RMS: 0.014, max: 0.116


INFO:pyscf.geomopt.berny_solver.132696934205296:1 Total step: RMS: 0.014, max: 0.116


1 Perfect transformation to cartesians in 5 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:1 Perfect transformation to cartesians in 5 iterations


1 * RMS(dcart): 4.45e-07, RMS(dq): 3.59e-07


INFO:pyscf.geomopt.berny_solver.132696934205296:1 * RMS(dcart): 4.45e-07, RMS(dq): 3.59e-07


1 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:1 Convergence criteria:


1 * Gradient RMS: 0.0515 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:1 * Gradient RMS: 0.0515 > 0.00015 => no


1 * Gradient maximum: 0.429 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:1 * Gradient maximum: 0.429 > 0.00045 => no


1 * Minimization on sphere: Minimization on sphere => no


INFO:pyscf.geomopt.berny_solver.132696934205296:1 * Minimization on sphere: Minimization on sphere => no



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.004924   1.236879   0.000000    0.004924  0.031379  0.000000
   C   1.103568   0.605049   0.000000    0.059468  0.002249  0.000000
   C   1.081800  -0.654303   0.000000    0.037700 -0.051503  0.000000
   C  -0.010309  -1.256329   0.000000   -0.010309 -0.050829  0.000000
   C  -1.078281  -0.632866   0.000000   -0.034181 -0.030066  0.000000
   C  -1.079606   0.599959   0.000000   -0.035506 -0.002841  0.000000
   C  -0.006421   2.648952   0.000000   -0.006421  0.046952  0.000000
   C   1.241169   3.171213  -0.000000   -0.012431  0.068313 -0.000000
   C   2.330758   2.562805  -0.000000    0.033058  0.062605 -0.000000
   C   2.359795   1.301340   0.000000    0.062095  0.006740  0.000000
   C   1.253839  -2.557152   0.000000    0.000239 -0.056952  0.000000
   C  -0.026282  -2.652447   0.000000   -0.026282 -0.050447  0.000000
   C  -1.292252  -2.537754  -0.0

INFO:pyscf.geomopt.berny_solver.132696934205296:2 Energy: -492.343494938


2 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:2 Hessian update information:


2 * Change: RMS: 0.00161, max: 0.139


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * Change: RMS: 0.00161, max: 0.139


2 Trust update: Fletcher's parameter: 0.908


INFO:pyscf.geomopt.berny_solver.132696934205296:2 Trust update: Fletcher's parameter: 0.908


2 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:2 Linear interpolation:


2 * Energies: -492.34349, -492.06284


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * Energies: -492.34349, -492.06284


2 * Derivatives: 0.234, 0.331


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * Derivatives: 0.234, 0.331


2 * No fit succeeded, staying in new point


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * No fit succeeded, staying in new point


2 Minimization on sphere was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:2 Minimization on sphere was performed:


2 * Trust radius: 0.6


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * Trust radius: 0.6


2 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * Number of negative eigenvalues: 0


2 * Lowest eigenvalue: 0.000588


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * Lowest eigenvalue: 0.000588


2 * lambda: -0.527


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * lambda: -0.527


2 Quadratic step: RMS: 0.028, max: 0.209


INFO:pyscf.geomopt.berny_solver.132696934205296:2 Quadratic step: RMS: 0.028, max: 0.209


2 * Predicted energy change: -0.315


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * Predicted energy change: -0.315


2 Total step: RMS: 0.028, max: 0.209


INFO:pyscf.geomopt.berny_solver.132696934205296:2 Total step: RMS: 0.028, max: 0.209


2 Perfect transformation to cartesians in 5 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:2 Perfect transformation to cartesians in 5 iterations


2 * RMS(dcart): 6.27e-07, RMS(dq): 3.92e-07


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * RMS(dcart): 6.27e-07, RMS(dq): 3.92e-07


2 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:2 Convergence criteria:


2 * Gradient RMS: 0.0366 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * Gradient RMS: 0.0366 > 0.00015 => no


2 * Gradient maximum: 0.294 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * Gradient maximum: 0.294 > 0.00045 => no


2 * Minimization on sphere: Minimization on sphere => no


INFO:pyscf.geomopt.berny_solver.132696934205296:2 * Minimization on sphere: Minimization on sphere => no



Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.001389   1.274331   0.000000   -0.006313  0.037452 -0.000000
   C   1.178673   0.601201   0.000000    0.075105 -0.003848 -0.000000
   C   1.132119  -0.735753   0.000000    0.050319 -0.081450 -0.000000
   C  -0.025770  -1.324617   0.000000   -0.015461 -0.068288 -0.000000
   C  -1.149371  -0.678594   0.000000   -0.071091 -0.045728 -0.000000
   C  -1.153093   0.595820   0.000000   -0.073487 -0.004139 -0.000000
   C  -0.016948   2.721872   0.000000   -0.010526  0.072920  0.000000
   C   1.229655   3.280760  -0.000000   -0.011514  0.109546  0.000000
   C   2.381971   2.631773  -0.000000    0.051213  0.068968  0.000000
   C   2.437001   1.311326   0.000000    0.077206  0.009987  0.000000
   C   1.293929  -2.627332   0.000000    0.040091 -0.070180  0.000000
   C  -0.055068  -2.735990   0.000000   -0.028786 -0.083543  0.000000
   C  -1.367868  -2.604284  -0.0

INFO:pyscf.geomopt.berny_solver.132696934205296:3 Energy: -492.683372171


3 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:3 Hessian update information:


3 * Change: RMS: 0.000675, max: 0.0495


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * Change: RMS: 0.000675, max: 0.0495


3 Trust update: Fletcher's parameter: 1.08


INFO:pyscf.geomopt.berny_solver.132696934205296:3 Trust update: Fletcher's parameter: 1.08


3 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:3 Linear interpolation:


3 * Energies: -492.68337, -492.34349


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * Energies: -492.68337, -492.34349


3 * Derivatives: 0.25, 0.44


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * Derivatives: 0.25, 0.44


3 * No fit succeeded, staying in new point


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * No fit succeeded, staying in new point


3 Pure RFO step was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:3 Pure RFO step was performed:


3 * Trust radius: 1.2


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * Trust radius: 1.2


3 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * Number of negative eigenvalues: 0


3 * Lowest eigenvalue: 0.000551


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * Lowest eigenvalue: 0.000551


3 * lambda: -0.256


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * lambda: -0.256


3 Quadratic step: RMS: 0.0312, max: 0.258


INFO:pyscf.geomopt.berny_solver.132696934205296:3 Quadratic step: RMS: 0.0312, max: 0.258


3 * Predicted energy change: -0.186


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * Predicted energy change: -0.186


3 Total step: RMS: 0.0312, max: 0.258


INFO:pyscf.geomopt.berny_solver.132696934205296:3 Total step: RMS: 0.0312, max: 0.258


3 Perfect transformation to cartesians in 6 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:3 Perfect transformation to cartesians in 6 iterations


3 * RMS(dcart): 2.38e-07, RMS(dq): 1.25e-07


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * RMS(dcart): 2.38e-07, RMS(dq): 1.25e-07


3 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:3 Convergence criteria:


3 * Gradient RMS: 0.0198 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * Gradient RMS: 0.0198 > 0.00015 => no


3 * Gradient maximum: 0.144 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * Gradient maximum: 0.144 > 0.00045 => no


3 * Step RMS: 0.0312 > 0.0012 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * Step RMS: 0.0312 > 0.0012 => no


3 * Step maximum: 0.259 > 0.0018 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:3 * Step maximum: 0.259 > 0.0018 => no



Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.003726   1.290040  -0.000000   -0.002337  0.015709 -0.000000
   C   1.244939   0.584809  -0.000000    0.066266 -0.016392 -0.000000
   C   1.175704  -0.814455  -0.000000    0.043586 -0.078702 -0.000000
   C  -0.038349  -1.366733  -0.000000   -0.012579 -0.042116 -0.000000
   C  -1.206924  -0.719704  -0.000000   -0.057553 -0.041110 -0.000000
   C  -1.218173   0.584513  -0.000000   -0.065080 -0.011308 -0.000000
   C  -0.013170   2.766478   0.000000    0.003778  0.044605 -0.000000
   C   1.232817   3.365833  -0.000000    0.003162  0.085074  0.000000
   C   2.424052   2.681978   0.000000    0.042081  0.050205  0.000000
   C   2.494065   1.311009   0.000000    0.057064 -0.000318  0.000000
   C   1.335848  -2.674485  -0.000000    0.041918 -0.047153 -0.000000
   C  -0.069358  -2.795201   0.000000   -0.014291 -0.059211 -0.000000
   C  -1.426229  -2.664902   0.0

INFO:pyscf.geomopt.berny_solver.132696934205296:4 Energy: -492.888287543


4 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:4 Hessian update information:


4 * Change: RMS: 0.000333, max: 0.0273


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * Change: RMS: 0.000333, max: 0.0273


4 Trust update: Fletcher's parameter: 1.1


INFO:pyscf.geomopt.berny_solver.132696934205296:4 Trust update: Fletcher's parameter: 1.1


4 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:4 Linear interpolation:


4 * Energies: -492.88829, -492.68337


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * Energies: -492.88829, -492.68337


4 * Derivatives: 0.157, 0.256


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * Derivatives: 0.157, 0.256


4 * No fit succeeded, staying in new point


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * No fit succeeded, staying in new point


4 Pure RFO step was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:4 Pure RFO step was performed:


4 * Trust radius: 1.2


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * Trust radius: 1.2


4 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * Number of negative eigenvalues: 0


4 * Lowest eigenvalue: 0.000478


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * Lowest eigenvalue: 0.000478


4 * lambda: -0.168


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * lambda: -0.168


4 Quadratic step: RMS: 0.0351, max: 0.277


INFO:pyscf.geomopt.berny_solver.132696934205296:4 Quadratic step: RMS: 0.0351, max: 0.277


4 * Predicted energy change: -0.132


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * Predicted energy change: -0.132


4 Total step: RMS: 0.0351, max: 0.277


INFO:pyscf.geomopt.berny_solver.132696934205296:4 Total step: RMS: 0.0351, max: 0.277


4 Perfect transformation to cartesians in 6 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:4 Perfect transformation to cartesians in 6 iterations


4 * RMS(dcart): 1.67e-07, RMS(dq): 1.06e-07


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * RMS(dcart): 1.67e-07, RMS(dq): 1.06e-07


4 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:4 Convergence criteria:


4 * Gradient RMS: 0.011 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * Gradient RMS: 0.011 > 0.00015 => no


4 * Gradient maximum: 0.0949 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * Gradient maximum: 0.0949 > 0.00045 => no


4 * Step RMS: 0.0351 > 0.0012 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * Step RMS: 0.0351 > 0.0012 => no


4 * Step maximum: 0.277 > 0.0018 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:4 * Step maximum: 0.277 > 0.0018 => no



Geometry optimization cycle 5
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.010095   1.291964  -0.000000   -0.006370  0.001924 -0.000000
   C   1.297714   0.563818  -0.000000    0.052775 -0.020991 -0.000000
   C   1.214761  -0.883595  -0.000000    0.039057 -0.069140 -0.000000
   C  -0.043581  -1.384459  -0.000000   -0.005233 -0.017726 -0.000000
   C  -1.251971  -0.750165  -0.000000   -0.045046 -0.030461  0.000000
   C  -1.282552   0.575671  -0.000000   -0.064379 -0.008842 -0.000000
   C  -0.010180   2.780463   0.000000    0.002989  0.013985 -0.000000
   C   1.238975   3.404604  -0.000000    0.006158  0.038771 -0.000000
   C   2.456583   2.695544   0.000000    0.032531  0.013565 -0.000000
   C   2.531631   1.300823   0.000000    0.037566 -0.010186 -0.000000
   C   1.382556  -2.689433  -0.000000    0.046708 -0.014948 -0.000000
   C  -0.070989  -2.824792   0.000000   -0.001630 -0.029591 -0.000000
   C  -1.463158  -2.712030   0.0

INFO:pyscf.geomopt.berny_solver.132696934205296:5 Energy: -493.028965083


5 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:5 Hessian update information:


5 * Change: RMS: 0.000416, max: 0.0319


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * Change: RMS: 0.000416, max: 0.0319


5 Trust update: Fletcher's parameter: 1.07


INFO:pyscf.geomopt.berny_solver.132696934205296:5 Trust update: Fletcher's parameter: 1.07


5 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:5 Linear interpolation:


5 * Energies: -493.02897, -492.88829


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * Energies: -493.02897, -492.88829


5 * Derivatives: 0.113, 0.168


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * Derivatives: 0.113, 0.168


5 * No fit succeeded, staying in new point


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * No fit succeeded, staying in new point


5 Pure RFO step was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:5 Pure RFO step was performed:


5 * Trust radius: 1.2


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * Trust radius: 1.2


5 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * Number of negative eigenvalues: 0


5 * Lowest eigenvalue: 0.000268


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * Lowest eigenvalue: 0.000268


5 * lambda: -0.129


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * lambda: -0.129


5 Quadratic step: RMS: 0.0388, max: 0.399


INFO:pyscf.geomopt.berny_solver.132696934205296:5 Quadratic step: RMS: 0.0388, max: 0.399


5 * Predicted energy change: -0.109


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * Predicted energy change: -0.109


5 Total step: RMS: 0.0388, max: 0.399


INFO:pyscf.geomopt.berny_solver.132696934205296:5 Total step: RMS: 0.0388, max: 0.399


5 Perfect transformation to cartesians in 6 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:5 Perfect transformation to cartesians in 6 iterations


5 * RMS(dcart): 1.68e-07, RMS(dq): 1.4e-07


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * RMS(dcart): 1.68e-07, RMS(dq): 1.4e-07


5 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:5 Convergence criteria:


5 * Gradient RMS: 0.0073 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * Gradient RMS: 0.0073 > 0.00015 => no


5 * Gradient maximum: 0.0675 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * Gradient maximum: 0.0675 > 0.00045 => no


5 * Step RMS: 0.0388 > 0.0012 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * Step RMS: 0.0388 > 0.0012 => no


5 * Step maximum: 0.4 > 0.0018 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:5 * Step maximum: 0.4 > 0.0018 => no



Geometry optimization cycle 6
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.019071   1.279477   0.000000   -0.008976 -0.012487  0.000000
   C   1.334839   0.539072   0.000000    0.037125 -0.024746  0.000000
   C   1.243098  -0.941593  -0.000000    0.028336 -0.057997  0.000000
   C  -0.046934  -1.383766  -0.000000   -0.003353  0.000694  0.000000
   C  -1.284336  -0.775864  -0.000000   -0.032365 -0.025700 -0.000000
   C  -1.345703   0.565186  -0.000000   -0.063151 -0.010485 -0.000000
   C  -0.003134   2.768943   0.000000    0.007046 -0.011519  0.000000
   C   1.248660   3.412470   0.000000    0.009685  0.007866  0.000000
   C   2.481692   2.693564   0.000000    0.025109 -0.001979  0.000000
   C   2.556041   1.284344   0.000000    0.024410 -0.016478 -0.000000
   C   1.423686  -2.675426  -0.000000    0.041130  0.014007  0.000000
   C  -0.070166  -2.830302   0.000000    0.000823 -0.005510  0.000000
   C  -1.485788  -2.745418   0.0

INFO:pyscf.geomopt.berny_solver.132696934205296:6 Energy: -493.143914947


6 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:6 Hessian update information:


6 * Change: RMS: 0.000493, max: 0.0499


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * Change: RMS: 0.000493, max: 0.0499


6 Trust update: Fletcher's parameter: 1.06


INFO:pyscf.geomopt.berny_solver.132696934205296:6 Trust update: Fletcher's parameter: 1.06


6 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:6 Linear interpolation:


6 * Energies: -493.14391, -493.02897


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * Energies: -493.14391, -493.02897


6 * Derivatives: 0.0992, 0.129


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * Derivatives: 0.0992, 0.129


6 * No fit succeeded, staying in new point


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * No fit succeeded, staying in new point


6 Pure RFO step was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:6 Pure RFO step was performed:


6 * Trust radius: 1.2


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * Trust radius: 1.2


6 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * Number of negative eigenvalues: 0


6 * Lowest eigenvalue: 0.000605


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * Lowest eigenvalue: 0.000605


6 * lambda: -0.115


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * lambda: -0.115


6 Quadratic step: RMS: 0.0411, max: 0.473


INFO:pyscf.geomopt.berny_solver.132696934205296:6 Quadratic step: RMS: 0.0411, max: 0.473


6 * Predicted energy change: -0.102


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * Predicted energy change: -0.102


6 Total step: RMS: 0.0411, max: 0.473


INFO:pyscf.geomopt.berny_solver.132696934205296:6 Total step: RMS: 0.0411, max: 0.473


6 Perfect transformation to cartesians in 8 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:6 Perfect transformation to cartesians in 8 iterations


6 * RMS(dcart): 9.5e-07, RMS(dq): 6.29e-05


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * RMS(dcart): 9.5e-07, RMS(dq): 6.29e-05


6 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:6 Convergence criteria:


6 * Gradient RMS: 0.00653 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * Gradient RMS: 0.00653 > 0.00015 => no


6 * Gradient maximum: 0.0719 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * Gradient maximum: 0.0719 > 0.00045 => no


6 * Step RMS: 0.042 > 0.0012 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * Step RMS: 0.042 > 0.0012 => no


6 * Step maximum: 0.493 > 0.0018 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:6 * Step maximum: 0.493 > 0.0018 => no



Geometry optimization cycle 7
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.028443   1.256846   0.000000   -0.009372 -0.022632  0.000000
   C   1.358825   0.516361   0.000000    0.023986 -0.022711  0.000000
   C   1.262986  -0.983263   0.000001    0.019888 -0.041670  0.000001
   C  -0.050341  -1.371373   0.000001   -0.003408  0.012392  0.000001
   C  -1.305058  -0.802072   0.000000   -0.020722 -0.026208  0.000000
   C  -1.404488   0.553352  -0.000000   -0.058784 -0.011833 -0.000000
   C   0.004576   2.739033  -0.000000    0.007711 -0.029910 -0.000000
   C   1.259950   3.398418  -0.000000    0.011290 -0.014053 -0.000000
   C   2.500083   2.679356  -0.000000    0.018390 -0.014208 -0.000000
   C   2.570635   1.266164   0.000000    0.014593 -0.018180  0.000000
   C   1.457681  -2.633005   0.000001    0.033995  0.042421  0.000001
   C  -0.070638  -2.810941   0.000001   -0.000472  0.019361  0.000001
   C  -1.499790  -2.776336   0.0

INFO:pyscf.geomopt.berny_solver.132696934205296:7 Energy: -493.243277417


7 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:7 Hessian update information:


7 * Change: RMS: 0.000407, max: 0.0258


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Change: RMS: 0.000407, max: 0.0258


7 Trust update: Fletcher's parameter: 0.976


INFO:pyscf.geomopt.berny_solver.132696934205296:7 Trust update: Fletcher's parameter: 0.976


7 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:7 Linear interpolation:


7 * Energies: -493.24328, -493.14391


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Energies: -493.24328, -493.14391


7 * Derivatives: 0.0706, 0.115


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Derivatives: 0.0706, 0.115


7 * Quartic interpolation was performed: t = -0.548


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Quartic interpolation was performed: t = -0.548


7 * Interpolated energy: -493.26459


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Interpolated energy: -493.26459


7 Pure RFO step was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:7 Pure RFO step was performed:


7 * Trust radius: 1.2


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Trust radius: 1.2


7 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Number of negative eigenvalues: 0


7 * Lowest eigenvalue: 0.000564


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Lowest eigenvalue: 0.000564


7 * lambda: -0.0545


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * lambda: -0.0545


7 Quadratic step: RMS: 0.0328, max: 0.273


INFO:pyscf.geomopt.berny_solver.132696934205296:7 Quadratic step: RMS: 0.0328, max: 0.273


7 * Predicted energy change: -0.0407


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Predicted energy change: -0.0407


7 Total step: RMS: 0.0542, max: 0.531


INFO:pyscf.geomopt.berny_solver.132696934205296:7 Total step: RMS: 0.0542, max: 0.531


7 Transformation did not converge in 20 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:7 Transformation did not converge in 20 iterations


7 * RMS(dcart): 0.055, RMS(dq): 0.0536


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * RMS(dcart): 0.055, RMS(dq): 0.0536


7 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:7 Convergence criteria:


7 * Gradient RMS: 0.00509 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Gradient RMS: 0.00509 > 0.00015 => no


7 * Gradient maximum: 0.0411 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Gradient maximum: 0.0411 > 0.00045 => no


7 * Step RMS: 0.0536 > 0.0012 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Step RMS: 0.0536 > 0.0012 => no


7 * Step maximum: 0.53 > 0.0018 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:7 * Step maximum: 0.53 > 0.0018 => no



Geometry optimization cycle 8
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.048593   1.213464  -0.000000   -0.020150 -0.043382 -0.000001
   C   1.369444   0.490524  -0.000001    0.010619 -0.025837 -0.000001
   C   1.278004  -1.015473  -0.000002    0.015018 -0.032210 -0.000003
   C  -0.056996  -1.336975  -0.000001   -0.006655  0.034398 -0.000002
   C  -1.333669  -0.832169  -0.000000   -0.028612 -0.030096 -0.000000
   C  -1.490738   0.545216   0.000000   -0.086251 -0.008136  0.000000
   C   0.020446   2.678207   0.000000    0.015870 -0.060826  0.000000
   C   1.279114   3.356398   0.000000    0.019164 -0.042020  0.000001
   C   2.519434   2.652936   0.000000    0.019351 -0.026420  0.000000
   C   2.575458   1.243087  -0.000000    0.004823 -0.023077 -0.000001
   C   1.492746  -2.550600  -0.000003    0.035064  0.082406 -0.000004
   C  -0.072746  -2.768808  -0.000001   -0.002108  0.042133 -0.000002
   C  -1.495241  -2.801117  -0.0

INFO:pyscf.geomopt.berny_solver.132696934205296:8 Energy: -493.262718193


8 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:8 Hessian update information:


8 * Change: RMS: 0.00083, max: 0.2


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Change: RMS: 0.00083, max: 0.2


8 Trust update: Fletcher's parameter: 0.477


INFO:pyscf.geomopt.berny_solver.132696934205296:8 Trust update: Fletcher's parameter: 0.477


8 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:8 Linear interpolation:


8 * Energies: -493.26272, -493.24328


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Energies: -493.26272, -493.24328


8 * Derivatives: -0.126, 0.101


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Derivatives: -0.126, 0.101


8 * Quartic interpolation was performed: t = 0.353


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Quartic interpolation was performed: t = 0.353


8 * Interpolated energy: -493.28319


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Interpolated energy: -493.28319


8 Pure RFO step was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:8 Pure RFO step was performed:


8 * Trust radius: 1.2


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Trust radius: 1.2


8 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Number of negative eigenvalues: 0


8 * Lowest eigenvalue: 0.000529


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Lowest eigenvalue: 0.000529


8 * lambda: -0.0592


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * lambda: -0.0592


8 Quadratic step: RMS: 0.0227, max: 0.218


INFO:pyscf.geomopt.berny_solver.132696934205296:8 Quadratic step: RMS: 0.0227, max: 0.218


8 * Predicted energy change: -0.0366


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Predicted energy change: -0.0366


8 Total step: RMS: 0.0236, max: 0.348


INFO:pyscf.geomopt.berny_solver.132696934205296:8 Total step: RMS: 0.0236, max: 0.348


8 Perfect transformation to cartesians in 5 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:8 Perfect transformation to cartesians in 5 iterations


8 * RMS(dcart): 6.79e-07, RMS(dq): 1.56e-06


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * RMS(dcart): 6.79e-07, RMS(dq): 1.56e-06


8 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:8 Convergence criteria:


8 * Gradient RMS: 0.0118 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Gradient RMS: 0.0118 > 0.00015 => no


8 * Gradient maximum: 0.178 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Gradient maximum: 0.178 > 0.00045 => no


8 * Step RMS: 0.0235 > 0.0012 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Step RMS: 0.0235 > 0.0012 => no


8 * Step maximum: 0.35 > 0.0018 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:8 * Step maximum: 0.35 > 0.0018 => no



Geometry optimization cycle 9
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.047840   1.211027  -0.000000    0.000753 -0.002436  0.000000
   C   1.355538   0.495501  -0.000001   -0.013906  0.004978  0.000000
   C   1.262515  -0.995002  -0.000002   -0.015490  0.020472 -0.000000
   C  -0.064811  -1.317303  -0.000001   -0.007814  0.019672 -0.000000
   C  -1.342105  -0.822581  -0.000000   -0.008435  0.009587 -0.000000
   C  -1.488715   0.561440   0.000000    0.002024  0.016224 -0.000000
   C   0.028533   2.670009   0.000000    0.008086 -0.008198  0.000000
   C   1.287813   3.342366   0.000000    0.008700 -0.014032  0.000000
   C   2.517297   2.646030   0.000000   -0.002136 -0.006906 -0.000000
   C   2.564916   1.244372  -0.000000   -0.010542  0.001285 -0.000000
   C   1.479468  -2.532154  -0.000003   -0.013277  0.018446 -0.000000
   C  -0.075515  -2.754453  -0.000001   -0.002769  0.014355 -0.000000
   C  -1.483124  -2.782367  -0.0

INFO:pyscf.geomopt.berny_solver.132696934205296:9 Energy: -493.319628973


9 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:9 Hessian update information:


9 * Change: RMS: 0.000454, max: 0.0557


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Change: RMS: 0.000454, max: 0.0557


9 Trust update: Fletcher's parameter: 1.55


INFO:pyscf.geomopt.berny_solver.132696934205296:9 Trust update: Fletcher's parameter: 1.55


9 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:9 Linear interpolation:


9 * Energies: -493.31963, -493.26272


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Energies: -493.31963, -493.26272


9 * Derivatives: 0.01, 0.125


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Derivatives: 0.01, 0.125


9 * Quartic interpolation was performed: t = -0.206


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Quartic interpolation was performed: t = -0.206


9 * Interpolated energy: -493.3206


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Interpolated energy: -493.3206


9 Pure RFO step was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:9 Pure RFO step was performed:


9 * Trust radius: 1.2


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Trust radius: 1.2


9 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Number of negative eigenvalues: 0


9 * Lowest eigenvalue: 0.000532


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Lowest eigenvalue: 0.000532


9 * lambda: -0.0486


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * lambda: -0.0486


9 Quadratic step: RMS: 0.0307, max: 0.356


INFO:pyscf.geomopt.berny_solver.132696934205296:9 Quadratic step: RMS: 0.0307, max: 0.356


9 * Predicted energy change: -0.0349


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Predicted energy change: -0.0349


9 Total step: RMS: 0.0321, max: 0.375


INFO:pyscf.geomopt.berny_solver.132696934205296:9 Total step: RMS: 0.0321, max: 0.375


9 Perfect transformation to cartesians in 5 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:9 Perfect transformation to cartesians in 5 iterations


9 * RMS(dcart): 3.1e-07, RMS(dq): 3.22e-07


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * RMS(dcart): 3.1e-07, RMS(dq): 3.22e-07


9 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:9 Convergence criteria:


9 * Gradient RMS: 0.00369 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Gradient RMS: 0.00369 > 0.00015 => no


9 * Gradient maximum: 0.0407 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Gradient maximum: 0.0407 > 0.00045 => no


9 * Step RMS: 0.0321 > 0.0012 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Step RMS: 0.0321 > 0.0012 => no


9 * Step maximum: 0.374 > 0.0018 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:9 * Step maximum: 0.374 > 0.0018 => no



Geometry optimization cycle 10
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.055987   1.186758  -0.000000   -0.008147 -0.024270  0.000000
   C   1.347031   0.489543  -0.000001   -0.008507 -0.005959 -0.000000
   C   1.261988  -0.991200  -0.000003   -0.000526  0.003802 -0.000001
   C  -0.069235  -1.293112  -0.000002   -0.004424  0.024191 -0.000000
   C  -1.350984  -0.828742  -0.000000   -0.008879 -0.006161 -0.000000
   C  -1.524508   0.570207   0.000000   -0.035793  0.008768  0.000000
   C   0.027332   2.640765   0.000001   -0.001201 -0.029244  0.000000
   C   1.289794   3.322096   0.000001    0.001981 -0.020271  0.000000
   C   2.517156   2.635860  -0.000000   -0.000142 -0.010170 -0.000000
   C   2.554276   1.239228  -0.000001   -0.010640 -0.005144 -0.000000
   C   1.484292  -2.492101  -0.000004    0.004823  0.040053 -0.000001
   C  -0.076247  -2.735723  -0.000002   -0.000732  0.018730 -0.000000
   C  -1.465426  -2.769280  -0.

INFO:pyscf.geomopt.berny_solver.132696934205296:10 Energy: -493.366966353


10 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:10 Hessian update information:


10 * Change: RMS: 0.00478, max: 0.196


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * Change: RMS: 0.00478, max: 0.196


10 Trust update: Fletcher's parameter: 1.36


INFO:pyscf.geomopt.berny_solver.132696934205296:10 Trust update: Fletcher's parameter: 1.36


10 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:10 Linear interpolation:


10 * Energies: -493.36697, -493.31963


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * Energies: -493.36697, -493.31963


10 * Derivatives: 0.0467, 0.0472


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * Derivatives: 0.0467, 0.0472


10 * No fit succeeded, staying in new point


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * No fit succeeded, staying in new point


10 Pure RFO step was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:10 Pure RFO step was performed:


10 * Trust radius: 1.2


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * Trust radius: 1.2


10 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * Number of negative eigenvalues: 0


10 * Lowest eigenvalue: 0.000104


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * Lowest eigenvalue: 0.000104


10 * lambda: -0.0705


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * lambda: -0.0705


10 Quadratic step: RMS: 0.0456, max: 0.528


INFO:pyscf.geomopt.berny_solver.132696934205296:10 Quadratic step: RMS: 0.0456, max: 0.528


10 * Predicted energy change: -0.069


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * Predicted energy change: -0.069


10 Total step: RMS: 0.0456, max: 0.528


INFO:pyscf.geomopt.berny_solver.132696934205296:10 Total step: RMS: 0.0456, max: 0.528


10 Perfect transformation to cartesians in 6 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:10 Perfect transformation to cartesians in 6 iterations


10 * RMS(dcart): 1.82e-07, RMS(dq): 1.21e-07


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * RMS(dcart): 1.82e-07, RMS(dq): 1.21e-07


10 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:10 Convergence criteria:


10 * Gradient RMS: 0.00379 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * Gradient RMS: 0.00379 > 0.00015 => no


10 * Gradient maximum: 0.0501 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * Gradient maximum: 0.0501 > 0.00045 => no


10 * Step RMS: 0.0456 > 0.0012 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * Step RMS: 0.0456 > 0.0012 => no


10 * Step maximum: 0.528 > 0.0018 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:10 * Step maximum: 0.528 > 0.0018 => no



Geometry optimization cycle 11
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.059464   1.154764  -0.000000   -0.003478 -0.031993  0.000000
   C   1.330871   0.482848  -0.000001   -0.016159 -0.006694 -0.000000
   C   1.261638  -0.978436  -0.000003   -0.000351  0.012764 -0.000000
   C  -0.071316  -1.262837  -0.000002   -0.002081  0.030275 -0.000000
   C  -1.351123  -0.837206  -0.000000   -0.000140 -0.008464 -0.000000
   C  -1.558242   0.583603   0.000000   -0.033734  0.013395 -0.000000
   C   0.010477   2.611710   0.000001   -0.016855 -0.029055  0.000000
   C   1.286634   3.297454   0.000001   -0.003160 -0.024641  0.000000
   C   2.512320   2.620928  -0.000000   -0.004836 -0.014932 -0.000000
   C   2.534825   1.233019  -0.000001   -0.019451 -0.006209 -0.000000
   C   1.487692  -2.443268  -0.000005    0.003400  0.048833 -0.000001
   C  -0.075190  -2.715362  -0.000002    0.001058  0.020361 -0.000000
   C  -1.431247  -2.740993  -0.

INFO:pyscf.geomopt.berny_solver.132696934205296:11 Energy: -493.432011927


11 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:11 Hessian update information:


11 * Change: RMS: 0.00114, max: 0.0884


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * Change: RMS: 0.00114, max: 0.0884


11 Trust update: Fletcher's parameter: 0.943


INFO:pyscf.geomopt.berny_solver.132696934205296:11 Trust update: Fletcher's parameter: 0.943


11 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:11 Linear interpolation:


11 * Energies: -493.43201, -493.36697


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * Energies: -493.43201, -493.36697


11 * Derivatives: 0.0555, 0.0705


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * Derivatives: 0.0555, 0.0705


11 * No fit succeeded, staying in new point


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * No fit succeeded, staying in new point


11 Pure RFO step was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:11 Pure RFO step was performed:


11 * Trust radius: 1.2


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * Trust radius: 1.2


11 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * Number of negative eigenvalues: 0


11 * Lowest eigenvalue: 0.00051


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * Lowest eigenvalue: 0.00051


11 * lambda: -0.0535


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * lambda: -0.0535


11 Quadratic step: RMS: 0.0403, max: 0.47


INFO:pyscf.geomopt.berny_solver.132696934205296:11 Quadratic step: RMS: 0.0403, max: 0.47


11 * Predicted energy change: -0.0467


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * Predicted energy change: -0.0467


11 Total step: RMS: 0.0403, max: 0.47


INFO:pyscf.geomopt.berny_solver.132696934205296:11 Total step: RMS: 0.0403, max: 0.47


11 Transformation did not converge in 20 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:11 Transformation did not converge in 20 iterations


11 * RMS(dcart): 0.0381, RMS(dq): 0.0399


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * RMS(dcart): 0.0381, RMS(dq): 0.0399


11 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:11 Convergence criteria:


11 * Gradient RMS: 0.0041 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * Gradient RMS: 0.0041 > 0.00015 => no


11 * Gradient maximum: 0.0487 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * Gradient maximum: 0.0487 > 0.00045 => no


11 * Step RMS: 0.0399 > 0.0012 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * Step RMS: 0.0399 > 0.0012 => no


11 * Step maximum: 0.469 > 0.0018 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:11 * Step maximum: 0.469 > 0.0018 => no



Geometry optimization cycle 12
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.057626   1.133005  -0.000000    0.001839 -0.021759 -0.000000
   C   1.306116   0.483719  -0.000001   -0.024755  0.000870 -0.000000
   C   1.253748  -0.960818  -0.000003   -0.007890  0.017618  0.000000
   C  -0.074032  -1.246706  -0.000002   -0.002716  0.016130  0.000000
   C  -1.349950  -0.854979  -0.000000    0.001173 -0.017773 -0.000000
   C  -1.569234   0.586512  -0.000000   -0.010993  0.002909 -0.000000
   C   0.004724   2.595241   0.000001   -0.005754 -0.016469 -0.000000
   C   1.285094   3.286790   0.000001   -0.001541 -0.010664  0.000000
   C   2.507222   2.616513  -0.000000   -0.005098 -0.004415  0.000000
   C   2.508606   1.237130  -0.000001   -0.026219  0.004111 -0.000000
   C   1.487490  -2.408948  -0.000004   -0.000201  0.034320  0.000000
   C  -0.068276  -2.707104  -0.000002    0.006914  0.008258  0.000000
   C  -1.400892  -2.713786  -0.

INFO:pyscf.geomopt.berny_solver.132696934205296:12 Energy: -493.469169375


12 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:12 Hessian update information:


12 * Change: RMS: 0.00076, max: 0.0478


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Change: RMS: 0.00076, max: 0.0478


12 Trust update: Fletcher's parameter: 0.795


INFO:pyscf.geomopt.berny_solver.132696934205296:12 Trust update: Fletcher's parameter: 0.795


12 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:12 Linear interpolation:


12 * Energies: -493.46917, -493.43201


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Energies: -493.46917, -493.43201


12 * Derivatives: 0.0135, 0.053


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Derivatives: 0.0135, 0.053


12 * Quartic interpolation was performed: t = -0.188


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Quartic interpolation was performed: t = -0.188


12 * Interpolated energy: -493.47047


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Interpolated energy: -493.47047


12 Pure RFO step was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:12 Pure RFO step was performed:


12 * Trust radius: 1.2


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Trust radius: 1.2


12 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Number of negative eigenvalues: 0


12 * Lowest eigenvalue: 0.000514


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Lowest eigenvalue: 0.000514


12 * lambda: -0.019


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * lambda: -0.019


12 Quadratic step: RMS: 0.0272, max: 0.221


INFO:pyscf.geomopt.berny_solver.132696934205296:12 Quadratic step: RMS: 0.0272, max: 0.221


12 * Predicted energy change: -0.0127


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Predicted energy change: -0.0127


12 Total step: RMS: 0.0322, max: 0.301


INFO:pyscf.geomopt.berny_solver.132696934205296:12 Total step: RMS: 0.0322, max: 0.301


12 Perfect transformation to cartesians in 6 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:12 Perfect transformation to cartesians in 6 iterations


12 * RMS(dcart): 5.91e-07, RMS(dq): 7.77e-07


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * RMS(dcart): 5.91e-07, RMS(dq): 7.77e-07


12 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:12 Convergence criteria:


12 * Gradient RMS: 0.00428 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Gradient RMS: 0.00428 > 0.00015 => no


12 * Gradient maximum: 0.0279 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Gradient maximum: 0.0279 > 0.00045 => no


12 * Step RMS: 0.0323 > 0.0012 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Step RMS: 0.0323 > 0.0012 => no


12 * Step maximum: 0.3 > 0.0018 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:12 * Step maximum: 0.3 > 0.0018 => no



Geometry optimization cycle 13
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.064536   1.108262  -0.000000   -0.006910 -0.024743  0.000000
   C   1.327900   0.478882  -0.000002    0.021784 -0.004837 -0.000000
   C   1.263744  -0.983136  -0.000004    0.009997 -0.022318 -0.000001
   C  -0.073922  -1.228094  -0.000002    0.000111  0.018613 -0.000001
   C  -1.377423  -0.853683  -0.000001   -0.027473  0.001296 -0.000000
   C  -1.607216   0.595994  -0.000000   -0.037981  0.009482 -0.000000
   C   0.082426   2.514018   0.000001    0.077702 -0.081223  0.000000
   C   1.277356   3.279912   0.000001   -0.007738 -0.006878  0.000000
   C   2.509852   2.639296  -0.000000    0.002630  0.022783 -0.000000
   C   2.520893   1.255123  -0.000002    0.012287  0.017993 -0.000001
   C   1.502455  -2.383462  -0.000006    0.014965  0.025486 -0.000001
   C  -0.062374  -2.685136  -0.000003    0.005902  0.021968 -0.000001
   C  -1.428441  -2.703785  -0.

INFO:pyscf.geomopt.berny_solver.132696934205296:13 Energy: -493.469149861


13 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:13 Hessian update information:


13 * Change: RMS: 0.00155, max: 0.0797


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * Change: RMS: 0.00155, max: 0.0797


13 Trust update: Fletcher's parameter: -0.00153


INFO:pyscf.geomopt.berny_solver.132696934205296:13 Trust update: Fletcher's parameter: -0.00153


13 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:13 Linear interpolation:


13 * Energies: -493.46915, -493.46917


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * Energies: -493.46915, -493.46917


13 * Derivatives: -0.023, 0.0215


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * Derivatives: -0.023, 0.0215


13 * Quartic interpolation was performed: t = 0.492


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * Quartic interpolation was performed: t = 0.492


13 * Interpolated energy: -493.47472


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * Interpolated energy: -493.47472


13 Minimization on sphere was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:13 Minimization on sphere was performed:


13 * Trust radius: 0.15


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * Trust radius: 0.15


13 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * Number of negative eigenvalues: 0


13 * Lowest eigenvalue: 0.000487


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * Lowest eigenvalue: 0.000487


13 * lambda: -0.237


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * lambda: -0.237


13 Quadratic step: RMS: 0.0068, max: 0.055


INFO:pyscf.geomopt.berny_solver.132696934205296:13 Quadratic step: RMS: 0.0068, max: 0.055


13 * Predicted energy change: -0.007


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * Predicted energy change: -0.007


13 Total step: RMS: 0.0168, max: 0.131


INFO:pyscf.geomopt.berny_solver.132696934205296:13 Total step: RMS: 0.0168, max: 0.131


13 Perfect transformation to cartesians in 5 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:13 Perfect transformation to cartesians in 5 iterations


13 * RMS(dcart): 5.22e-08, RMS(dq): 4.32e-06


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * RMS(dcart): 5.22e-08, RMS(dq): 4.32e-06


13 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:13 Convergence criteria:


13 * Gradient RMS: 0.00463 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * Gradient RMS: 0.00463 > 0.00015 => no


13 * Gradient maximum: 0.0463 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * Gradient maximum: 0.0463 > 0.00045 => no


13 * Minimization on sphere: Minimization on sphere => no


INFO:pyscf.geomopt.berny_solver.132696934205296:13 * Minimization on sphere: Minimization on sphere => no



Geometry optimization cycle 14
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.052623   1.126142  -0.000000    0.011913  0.017880 -0.000000
   C   1.315721   0.488203  -0.000001   -0.012180  0.009322  0.000000
   C   1.262374  -0.969173  -0.000003   -0.001370  0.013963  0.000001
   C  -0.066603  -1.251887  -0.000002    0.007319 -0.023793  0.000001
   C  -1.353414  -0.865374  -0.000000    0.024009 -0.011691  0.000000
   C  -1.570920   0.584767  -0.000000    0.036296 -0.011226 -0.000000
   C   0.047983   2.554997   0.000001   -0.034443  0.040980 -0.000000
   C   1.265929   3.294772   0.000001   -0.011427  0.014860 -0.000000
   C   2.504101   2.642604  -0.000000   -0.005750  0.003308  0.000000
   C   2.512196   1.256944  -0.000002   -0.008697  0.001821  0.000001
   C   1.493532  -2.423347  -0.000004   -0.008924 -0.039886  0.000002
   C  -0.057108  -2.712458  -0.000002    0.005265 -0.027322  0.000001
   C  -1.410759  -2.703696  -0.

INFO:pyscf.geomopt.berny_solver.132696934205296:14 Energy: -493.482213224


14 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:14 Hessian update information:


14 * Change: RMS: 0.000946, max: 0.0474


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * Change: RMS: 0.000946, max: 0.0474


14 Trust update: Fletcher's parameter: 1.87


INFO:pyscf.geomopt.berny_solver.132696934205296:14 Trust update: Fletcher's parameter: 1.87


14 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:14 Linear interpolation:


14 * Energies: -493.48221, -493.46917


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * Energies: -493.48221, -493.46917


14 * Derivatives: 0.00749, 0.0184


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * Derivatives: 0.00749, 0.0184


14 * Quartic interpolation was performed: t = -0.626


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * Quartic interpolation was performed: t = -0.626


14 * Interpolated energy: -493.48459


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * Interpolated energy: -493.48459


14 Minimization on sphere was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:14 Minimization on sphere was performed:


14 * Trust radius: 0.29


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * Trust radius: 0.29


14 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * Number of negative eigenvalues: 0


14 * Lowest eigenvalue: 0.000521


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * Lowest eigenvalue: 0.000521


14 * lambda: -0.0409


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * lambda: -0.0409


14 Quadratic step: RMS: 0.0136, max: 0.0985


INFO:pyscf.geomopt.berny_solver.132696934205296:14 Quadratic step: RMS: 0.0136, max: 0.0985


14 * Predicted energy change: -0.00663


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * Predicted energy change: -0.00663


14 Total step: RMS: 0.0203, max: 0.163


INFO:pyscf.geomopt.berny_solver.132696934205296:14 Total step: RMS: 0.0203, max: 0.163


14 Perfect transformation to cartesians in 4 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:14 Perfect transformation to cartesians in 4 iterations


14 * RMS(dcart): 8.15e-07, RMS(dq): 3.07e-05


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * RMS(dcart): 8.15e-07, RMS(dq): 3.07e-05


14 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:14 Convergence criteria:


14 * Gradient RMS: 0.00316 > 0.00015 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * Gradient RMS: 0.00316 > 0.00015 => no


14 * Gradient maximum: 0.0213 > 0.00045 => no


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * Gradient maximum: 0.0213 > 0.00045 => no


14 * Minimization on sphere: Minimization on sphere => no


INFO:pyscf.geomopt.berny_solver.132696934205296:14 * Minimization on sphere: Minimization on sphere => no



Geometry optimization cycle 15
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.032520   1.120546   0.000000    0.020103 -0.005596  0.000000
   C   1.318019   0.492555  -0.000001    0.002298  0.004352  0.000000
   C   1.276877  -0.966598  -0.000001    0.014503  0.002575  0.000002
   C  -0.044826  -1.272833  -0.000001    0.021777 -0.020946  0.000001
   C  -1.333352  -0.889073  -0.000000    0.020062 -0.023699  0.000000
   C  -1.537442   0.571628  -0.000000    0.033478 -0.013140 -0.000000
   C   0.058804   2.534483   0.000001    0.010821 -0.020514  0.000000
   C   1.229759   3.306164   0.000001   -0.036170  0.011391 -0.000000
   C   2.487901   2.668055  -0.000000   -0.016201  0.025451 -0.000000
   C   2.504897   1.279455  -0.000002   -0.007299  0.022511 -0.000000
   C   1.495284  -2.460584  -0.000001    0.001753 -0.037237  0.000003
   C  -0.033139  -2.737725  -0.000001    0.023969 -0.025267  0.000001
   C  -1.397606  -2.671963  -0.

INFO:pyscf.geomopt.berny_solver.132696934205296:15 Energy: -493.490941627


15 Pseudoinverse gap of only: 1.3e+03


INFO:pyscf.geomopt.berny_solver.132696934205296:15 Pseudoinverse gap of only: 1.3e+03


15 Hessian update information:


INFO:pyscf.geomopt.berny_solver.132696934205296:15 Hessian update information:


15 * Change: RMS: 0.000467, max: 0.0156


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Change: RMS: 0.000467, max: 0.0156


15 Trust update: Fletcher's parameter: 1.32


INFO:pyscf.geomopt.berny_solver.132696934205296:15 Trust update: Fletcher's parameter: 1.32


15 Linear interpolation:


INFO:pyscf.geomopt.berny_solver.132696934205296:15 Linear interpolation:


15 * Energies: -493.49094, -493.48221


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Energies: -493.49094, -493.48221


15 * Derivatives: -2.55e-13, 0.014


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Derivatives: -2.55e-13, 0.014


15 * Quartic interpolation was performed: t = 9.9e-12


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Quartic interpolation was performed: t = 9.9e-12


15 * Interpolated energy: -493.49094


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Interpolated energy: -493.49094


15 Pure RFO step was performed:


INFO:pyscf.geomopt.berny_solver.132696934205296:15 Pure RFO step was performed:


15 * Trust radius: 0.58


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Trust radius: 0.58


15 * Number of negative eigenvalues: 0


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Number of negative eigenvalues: 0


15 * Lowest eigenvalue: 0.00236


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Lowest eigenvalue: 0.00236


15 * lambda: -1.58e-16


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * lambda: -1.58e-16


15 Quadratic step: RMS: 1.21e-08, max: 9.78e-08


INFO:pyscf.geomopt.berny_solver.132696934205296:15 Quadratic step: RMS: 1.21e-08, max: 9.78e-08


15 * Predicted energy change: -7.88e-17


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Predicted energy change: -7.88e-17


15 Total step: RMS: 1.21e-08, max: 9.78e-08


INFO:pyscf.geomopt.berny_solver.132696934205296:15 Total step: RMS: 1.21e-08, max: 9.78e-08


15 Perfect transformation to cartesians in 1 iterations


INFO:pyscf.geomopt.berny_solver.132696934205296:15 Perfect transformation to cartesians in 1 iterations


15 * RMS(dcart): 4.32e-12, RMS(dq): 1.25e-08


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * RMS(dcart): 4.32e-12, RMS(dq): 1.25e-08


15 Convergence criteria:


INFO:pyscf.geomopt.berny_solver.132696934205296:15 Convergence criteria:


15 * Gradient RMS: 2.84e-11 < 0.00015 => OK


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Gradient RMS: 2.84e-11 < 0.00015 => OK


15 * Gradient maximum: 2.3e-10 < 0.00045 => OK


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Gradient maximum: 2.3e-10 < 0.00045 => OK


15 * Step RMS: 1.25e-08 < 0.0012 => OK


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Step RMS: 1.25e-08 < 0.0012 => OK


15 * Step maximum: 9.78e-08 < 0.0018 => OK


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * Step maximum: 9.78e-08 < 0.0018 => OK


15 * All criteria matched


INFO:pyscf.geomopt.berny_solver.132696934205296:15 * All criteria matched


Optimized coordinates:
[[-6.14537181e-02  2.11752577e+00  6.04684316e-07]
 [ 2.49069503e+00  9.30793982e-01 -1.60150917e-06]
 [ 2.41294761e+00 -1.82660570e+00 -1.86178369e-06]
 [-8.47086682e-02 -2.40530582e+00 -1.21865312e-06]
 [-2.51967004e+00 -1.68010354e+00 -4.32236788e-07]
 [-2.90534445e+00  1.08021975e+00 -2.26765389e-07]
 [ 1.11123685e-01  4.78947938e+00  1.57119218e-06]
 [ 2.32390841e+00  6.24774369e+00  1.39294175e-06]
 [ 4.70145082e+00  5.04189340e+00 -8.61238621e-07]
 [ 4.73356851e+00  2.41781911e+00 -3.07752795e-06]
 [ 2.82567795e+00 -4.64983064e+00 -1.98484011e-06]
 [-6.26236944e-02 -5.17355035e+00 -1.53812948e-06]
 [-2.64109195e+00 -5.04927813e+00 -7.30619154e-07]
 [ 1.86492349e+00  8.26582309e+00  3.30941740e-06]
 [ 6.46944109e+00  6.11099542e+00 -1.46136917e-06]
 [ 6.58470827e+00  1.52085993e+00 -5.30441758e-06]
 [ 4.48163084e+00 -5.87856403e+00  1.27894481e-05]
 [-4.12948752e+00 -6.59053976e+00 -6.24403678e-07]
 [-7.05982890e+00 -4.50823170e+00 -1.18955941e-06]
 [-6.905

In [ ]:
print("\nStarting Tier 1b: Single Point Energy & Ground State Characterization...")

# Perform a more accurate single point calculation on the optimized geometry
mf_final = dft.UKS(mol)
mf_final.xc = 'b3lyp'
mf_final.grids.level = 5  # Increased grid for better accuracy
mf_final.kernel()

# Analyze the results
print(f"Final UKS Energy: {mf_final.e_tot} Hartree")
print(f"Converged SCF: {mf_final.converged}")
print(f"⟨S²⟩ before annihilation: {mf_final.spin_square()[0]}")
print(f"⟨S²⟩ after annihilation: {mf_final.spin_square()[1]}")

# Criterion 1: Check if the ground state is indeed a doublet (S=1/2)
# For a perfect doublet, ⟨S²⟩ should be 0.75
s2_value = mf_final.spin_square()[1]
print(f"\n--- Criterion 1: Ground State Spin ---")
print(f"Calculated ⟨S²⟩ = {s2_value:.4f}")
print(f"Ideal ⟨S²⟩ for a pure S=1/2 state = 0.7500")

if 0.70 < s2_value < 0.80:
    print("✓ Ground state is a good doublet (S=1/2).")
else:
    print("✗ Ground state may not be a pure doublet. Check for spin contamination.")


Starting Tier 1b: Single Point Energy & Ground State Characterization...


******** <class 'pyscf.dft.uks.UKS'> ********
method = UKS
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
diis_damp = 0
SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmpebpzw4ym
max_memory 4000 MB (current use 342 MB)
number electrons alpha = 44  beta = 43
XC library pyscf.dft.libxc version 7.0.0
    S. Lehtola, C. Steigemann, M. J.T. Oliveira, and M. A.L. Marques.,  SoftwareX 7, 1–5 (2018)
XC functionals = b3lyp
    P. J. Stephens, F. J. Devlin, C. F. Chabalowski, and M. J. Frisch.,  J. Phys. Chem. 98, 11623 (1994)
radial grids: 
    Treutler-Ahlrichs [JCP 102, 346 (1995); DOI:10.1063/1.469408] (M4) radial grids
    
becke partition: Becke, JCP 88, 2547 (1988); DOI:10.1063/1.454033
pruning grids: <function nwchem_prune at 0x78a

In [ ]:
print("\nStarting Tier 1c: Calculating Energy Gap to First Excited State...")

# We need to find the energy of the triplet state (S=3/2)
# To do this, we run a calculation with spin=3 (multiplicity = 4, for a triplet)

# Create a molecule object for the triplet state
mol_triplet = gto.M(
    atom=phenalenyl_xyz,
    basis='def2-svp',
    charge=-1,
    spin=3,  # Triplet: 2S+1=4 -> S=3/2
    verbose=0
)

# Run the triplet calculation
mf_triplet = dft.UKS(mol_triplet)
mf_triplet.xc = 'b3lyp'
mf_triplet.kernel()

# Calculate the energy gap
energy_doublet = mf_final.e_tot
energy_triplet = mf_triplet.e_tot
delta_E = (energy_triplet - energy_doublet) * 627.509  # Convert Hartree to kcal/mol

print(f"Doublet (S=1/2) Energy: {energy_doublet} Ha")
print(f"Triplet (S=3/2) Energy: {energy_triplet} Ha")
print(f"ΔE (Triplet - Doublet) = {delta_E:.2f} kcal/mol")

print("\n--- Criterion 2: Energy Gap ---")
if delta_E > 5.0:  # A reasonable threshold for a significant gap
    print(f"✓ Energy gap is large ({delta_E:.2f} kcal/mol). Good qubit stability.")
else:
    print(f"✗ Energy gap is small ({delta_E:.2f} kcal/mol). The state may be easily disturbed.")


Starting Tier 1c: Calculating Energy Gap to First Excited State...
Doublet (S=1/2) Energy: -492.06280593221265 Ha
Triplet (S=3/2) Energy: -498.31967628628865 Ha
ΔE (Triplet - Doublet) = -3926.24 kcal/mol

--- Criterion 2: Energy Gap ---
✗ Energy gap is small (-3926.24 kcal/mol). The state may be easily disturbed.


In [7]:
print("\n" + "="*50)
print("TIER 1 SCREENING SUMMARY: PHENALENYL RADICAL")
print("="*50)

# Criterion 1 Summary (Spin purity)
s2_value = mf_final.spin_square()[1]
c1_pass = 0.70 < s2_value < 0.80
print(f"Criterion 1 (Pure S=1/2 GS): {'PASS' if c1_pass else 'FAIL'} - ⟨S²⟩ = {s2_value:.4f}")

# Criterion 2 Summary (Excited state gap)
c2_pass = delta_E > 5.0
print(f"Criterion 2 (Energy Gap):    {'PASS' if c2_pass else 'FAIL'} - ΔE = {delta_E:.2f} kcal/mol")

# Criterion 3 Proxy (Spin density localization → coherence)
print(f"\n--- Preliminary Check for Criterion 3 (Coherence) ---")
pop, charges = mf_final.mulliken_pop()
print("Mulliken spin population per atom:")
for i, q in enumerate(charges):
    print(f"Atom {i+1}: {q:.4f}")
print("Good sign: Spin density should be delocalized on carbons, not localized on hydrogens.")

# Overall Recommendation
if c1_pass and c2_pass:
    print("\n🎉 TIER 1 PASSED. This molecule is a promising candidate. Proceed to Tier 2.")
    print("Next steps in Tier 2:")
    print("  1. Calculate g-tensors and Hyperfine couplings (Criterion 3)")
    print("  2. Calculate transition dipole moments (Criterion 5)")
else:
    print("\n❌ TIER 1 FAILED. Do not proceed. Select a new candidate molecule.")



TIER 1 SCREENING SUMMARY: PHENALENYL RADICAL
Criterion 1 (Pure S=1/2 GS): FAIL - ⟨S²⟩ = 2.2222
Criterion 2 (Energy Gap):    FAIL - ΔE = -3926.24 kcal/mol

--- Preliminary Check for Criterion 3 (Coherence) ---
 ** Mulliken pop       alpha | beta **
pop of  0 C 1s        0.99511 | 0.99514   
pop of  0 C 2s        0.49385 | 0.49867   
pop of  0 C 2px       0.51300 | 0.51974   
pop of  0 C 2py       0.50162 | 0.50679   
pop of  0 C 2pz       0.52177 | 0.53307   
pop of  1 C 1s        0.99519 | 0.99515   
pop of  1 C 2s        0.49894 | 0.49207   
pop of  1 C 2px       0.49752 | 0.49058   
pop of  1 C 2py       0.51586 | 0.51052   
pop of  1 C 2pz       0.53414 | 0.50625   
pop of  2 C 1s        0.99581 | 0.99598   
pop of  2 C 2s        0.51135 | 0.54672   
pop of  2 C 2px       0.45225 | 0.53324   
pop of  2 C 2py       0.46046 | 0.49139   
pop of  2 C 2pz       0.50568 | 0.54321   
pop of  3 C 1s        0.99540 | 0.99531   
pop of  3 C 2s        0.50049 | 0.48830   
pop of  3 C 2px     